services:
  postgres_db:
    image: postgres:13
    environment:
      POSTGRES_DB: students
      POSTGRES_USER: berat
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
